/*
 * Copyright (c) 2019 WSO2 Inc. (http:www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AutoscalePolicyListerExpansion allows custom methods to be added to
// AutoscalePolicyLister.
type AutoscalePolicyListerExpansion interface{}

// AutoscalePolicyNamespaceListerExpansion allows custom methods to be added to
// AutoscalePolicyNamespaceLister.
type AutoscalePolicyNamespaceListerExpansion interface{}

// CellListerExpansion allows custom methods to be added to
// CellLister.
type CellListerExpansion interface{}

// CellNamespaceListerExpansion allows custom methods to be added to
// CellNamespaceLister.
type CellNamespaceListerExpansion interface{}

// CompositeListerExpansion allows custom methods to be added to
// CompositeLister.
type CompositeListerExpansion interface{}

// CompositeNamespaceListerExpansion allows custom methods to be added to
// CompositeNamespaceLister.
type CompositeNamespaceListerExpansion interface{}

// GatewayListerExpansion allows custom methods to be added to
// GatewayLister.
type GatewayListerExpansion interface{}

// GatewayNamespaceListerExpansion allows custom methods to be added to
// GatewayNamespaceLister.
type GatewayNamespaceListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// ServiceNamespaceListerExpansion allows custom methods to be added to
// ServiceNamespaceLister.
type ServiceNamespaceListerExpansion interface{}

// TokenServiceListerExpansion allows custom methods to be added to
// TokenServiceLister.
type TokenServiceListerExpansion interface{}

// TokenServiceNamespaceListerExpansion allows custom methods to be added to
// TokenServiceNamespaceLister.
type TokenServiceNamespaceListerExpansion interface{}
