/*
 * Copyright (c) 2018 WSO2 Inc. (http:www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	vickv1alpha1 "github.com/wso2/product-vick/system/controller/pkg/apis/vick/v1alpha1"
	versioned "github.com/wso2/product-vick/system/controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/wso2/product-vick/system/controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/wso2/product-vick/system/controller/pkg/client/listers/vick/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TokenServiceInformer provides access to a shared informer and lister for
// TokenServices.
type TokenServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TokenServiceLister
}

type tokenServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTokenServiceInformer constructs a new informer for TokenService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTokenServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTokenServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTokenServiceInformer constructs a new informer for TokenService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTokenServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VickV1alpha1().TokenServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VickV1alpha1().TokenServices(namespace).Watch(options)
			},
		},
		&vickv1alpha1.TokenService{},
		resyncPeriod,
		indexers,
	)
}

func (f *tokenServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTokenServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tokenServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vickv1alpha1.TokenService{}, f.defaultInformer)
}

func (f *tokenServiceInformer) Lister() v1alpha1.TokenServiceLister {
	return v1alpha1.NewTokenServiceLister(f.Informer().GetIndexer())
}
