apiVersion: mesh.cellery.io/v1alpha1
kind: Cell
metadata:
  name: hr
  annotations:
    mesh.cellery.io/cell-image-org: cellery-samples
    mesh.cellery.io/cell-image-name: hr
    mesh.cellery.io/cell-image-version: 1.0.0
spec:
  gatewayTemplate:
    spec:
      type: MicroGateway
      http:
      - context: info
        definitions:
        - path: /
          method: GET
        backend: hr
        global: false
        authenticate: true
  servicesTemplates:
  - metadata:
      name: hr
    spec:
#      autoscaling:
#        policy:
#          minReplicas: 0
      container:
        image: docker.io/celleryio/sampleapp-hr
        ports:
        - containerPort: 8080
        env:
        - name: employee_api_url
          value: http://employee--gateway-service/employee
        - name: stock_api_url
          value: http://stock-options--gateway-service/stock
      servicePort: 80
  - metadata:
      name: debug
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/k8s-debug-tools
      servicePort: 80
#  stsTemplate:
#    spec:
#      interceptMode: None
