apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.vick.wso2.com
spec:
  group: vick.wso2.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Service
    plural: services
    singular: service
    shortNames:
    - vservice
    - vsvc
  additionalPrinterColumns:
  - name: Available-Replicas
    type: integer
    description: Number of replicas available for this service
    JSONPath: .status.availableReplicas
  - name: Cell
    type: string
    description: Owner cell of this service
    JSONPath: .status.ownerCell
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
