apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-controller
  namespace: vick-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vick-controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: vick-controller
    spec:
      containers:
      - name: vick-controller
        image: wso2vick/vick-controller
      serviceAccountName: vick-controller
