apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wso2-cell-outbound-interceptor
  # Filter needs to be added in the istio-system namespace to be applied to all envoy sidecars.
  namespace: istio-system
spec:
  workloadLabels:
    # We filter the pods to apply this filter based on cell name. We expect the Pods within a cell to have this label.
    vick.wso2.com/cell: wso2-cell
  filters:
  - insertPosition:
      index: FIRST
    listenerMatch:
      # Intercepting all HTTP traffic going out of the Pods
      listenerType: SIDECAR_OUTBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:
      grpc_service:
        google_grpc:
          # Cell STS service which will intercept the outbound call and manipulate headers etc.
          target_uri: wso2-cell--sts-service:80
          stat_prefix: "ext_authz"
        timeout: 10s
