apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-metrics-prometheus
  namespace: vick-system
  labels:
    app: k8s-metrics-prometheus
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: k8s-metrics-prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.6.1
          name: k8s-metrics-prometheus
          imagePullPolicy: Always
          args:
            - --config.file=/etc/config/prometheus.yaml
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: k8s-metrics-prometheus-conf
              mountPath: "/etc/config/"
      serviceAccountName: k8s-metrics-prometheus
      volumes:
        - name: k8s-metrics-prometheus-conf
          configMap:
            name: k8s-metrics-prometheus-conf
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-metrics-prometheus
  namespace: vick-system
  labels:
    app: k8s-metrics-prometheus
spec:
  selector:
    app: k8s-metrics-prometheus
  ports:
    - name: http-prometheus
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-metrics-prometheus
  namespace: vick-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-metrics-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-metrics-prometheus
subjects:
  - kind: ServiceAccount
    name: k8s-metrics-prometheus
    namespace: vick-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-metrics-prometheus
