apiVersion: mesh.cellery.io/v1alpha2
kind: Cell
metadata:
  name: hr
  annotations:
    mesh.cellery.io/cell-image-org: cellery-samples
    mesh.cellery.io/cell-image-name: hr
    mesh.cellery.io/cell-image-version: 1.0.0
spec:
  gateway:
    spec:
      ingress:
        http:
        - context: /info
          definitions:
          - path: /
            method: GET
          port: 80
          destination: 
            host: hr
            port: 80
  components:
  - metadata:
      name: hr
    spec:
      scalingPolicy:
        replicas: 1
      template:
        containers:
        - image: docker.io/celleryio/sampleapp-hr
          name: hr
          env:
          - name: employee_api_url
            value: http://employee--gateway-service/employee
          - name: stock_api_url
            value: http://stock-options--gateway-service/stock
          resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      ports:
      - port: 80
        protocol: HTTP
        targetPort: 8080
  - metadata:
      name: debug
    spec:
      scalingPolicy:
        replicas: 1
      template:
        containers:
        - name: debug
          image: docker.io/mirage20/k8s-debug-tools
  sts:
    spec:
      interceptMode: None
